### ISSUE TITLE
Ex 2 - seneca.log.quietundefined

### ISSUE THREAD

**Issue by conolan** [senecajs/seneca-in-practice#43]
I got this with my own version: 

```
             ACTUAL                                  EXPECTED                
```

"{ answer: '--seneca.log.quietundefined' }" !=    "{ answer: 3 }"  
   "{ answer: 3 }"                     !=    ""    

Used solution, as published and got this

   "{ answer: NaN }"                   !=    "{ answer: 3 }"  
   "{ answer: 3 }"                     !=    ""

**Comment by marcopiraccini** [comment]
Have you passed the params? Something like: `seneca-in-practice run mysolution.js 2 3` ?

**Comment by conolan** [comment]
Just tried passing params, same result.

**Comment by marcopiraccini** [comment]
...mmm...cannot reproduce. Which OS are you using?

**Comment by marcopiraccini** [comment]
(also, are you using `seneca-in-practice` globally installed?)

**Comment by conolan** [comment]
Using crome on mac. Globally installed (-g) but am using in a different folder so I can keep my files for each exercise.

**Comment by marcopiraccini** [comment]
The only change done on this exercise is:
`this.submissionArgs = [process.cwd() + '/' + this.submission, process.argv[3], process.argv[4], '--seneca.log.quiet'] // TODO: verify portability`

to:

`this.submissionArgs = [process.cwd() + '/' + this.submission, process.argv[4], process.argv[5], '--seneca.log.quiet'] // TODO: verify portability`

For some reason, in OSx  it seems that `process.argv` is different from Linux. @piccoloaiutante can you check that? If so, we can have this problem also on other exercices

**Comment by marcopiraccini** [comment]
This is the commit: https://github.com/senecajs/seneca-in-practice/commit/8114cb1d24bb8a4b75219bba7afcffc9e7cd7323

Here the `console.log` of `process.argv` in Linux, where the numbers are in position 4 and 5:

```
⇒ seneca-in-practice run solution_client.js 2 3    
PROCESS:.ARGV [ '/home/marco/.nvm/versions/node/v4.2.4/bin/node',
  '/home/marco/.nvm/versions/node/v4.2.4/bin/seneca-in-practice',
  'run',
  'solution_client.js',
  '2',
  '3' ]
{ answer: 5 }
```

**Comment by marcopiraccini** [comment]
Cannot reproduce also with mac: 
![seneca](https://cloud.githubusercontent.com/assets/668050/15148384/457a8bfa-16c5-11e6-942e-9e44732e910c.png)

**Comment by irelandm** [comment]
The problem is that different parameter numbers are needed if using node to run the client, compared to using seneca-in-practice to run it, when the params are offset by 1.

Here's my output with param logging on:

marki:~/Dev/nodeschool/sip$ node client.js 3 4
params:
0: node
1: /Users/marki/Dev/nodeschool/sip/client.js
2: 3
3: 4
params end
2016-05-10T14:26:08.515Z o8dqh35rkn0n/1462890368506/8706/- INFO hello   Seneca/2.0.1/o8dqh35rkn0n/1462890368506/8706/-  
2016-05-10T14:26:08.734Z osfneiuhlcp3/1462890368731/8706/- INFO hello   Seneca/2.0.1/osfneiuhlcp3/1462890368731/8706/-  
{ answer: 7 }
{ answer: 7 }

marki:~/Dev/nodeschool/sip$ seneca-in-practice run client.js
params:
0: /Users/marki/.nvm/versions/node/v0.12.12/bin/node
1: /Users/marki/.nvm/versions/node/v0.12.12/lib/node_modules/seneca-in-practice/problems/client/seneca-client-executor.js
2: /Users/marki/Dev/nodeschool/sip/client.js
3: undefined
4: undefined
5: --seneca.log.quiet
params end
{ answer: NaN }
{ answer: NaN }

marki:~/Dev/nodeschool/sip$ seneca-in-practice run client.js 5 6
params:
0: /Users/marki/.nvm/versions/node/v0.12.12/bin/node
1: /Users/marki/.nvm/versions/node/v0.12.12/lib/node_modules/seneca-in-practice/problems/client/seneca-client-executor.js
2: /Users/marki/Dev/nodeschool/sip/client.js
3: 5
4: 6
5: --seneca.log.quiet
params end
{ answer: NaN }
{ answer: NaN }
marki:~/Dev/nodeschool/sip$ seneca-in-practice verify client.js

Your submission results compared to the expected:

```
             ACTUAL                                  EXPECTED                 
```

────────────────────────────────────────────────────────────────────────────────

   "params:"                           !=    "{ answer: 9 }"  
   "0: /Users/marki/.nvm/versions/node/v0.12.12/bin/node" !=    ""  
   "2: /Users/marki/Dev/nodeschool/sip/client.js" !=  
   "3: 2"                              !=  
   "4: 7"                              !=  
   "5: --seneca.log.quiet"             !=  
   "params end"                        !=  
   "{ answer: NaN }"                   !=  
   "{ answer: NaN }"                   !=  
   ""                                  !=                                       

────────────────────────────────────────────────────────────────────────────────

✗ Submission results match expected

# FAIL

Your solution to Client didn't pass. Try again!

**Comment by irelandm** [comment]
NB I previously noted this in my second comment on https://github.com/senecajs/seneca-in-practice/issues/33

**Comment by irelandm** [comment]
I think this also affects other exercises and I just switched the param number before running and verifying. Other nodeschool workshops have got around this, e.g. https://github.com/workshopper/workshopper-exercise/blob/master/execute.js

**Comment by marcopiraccini** [comment]
Yes, that make sense. Tnx @irelandm for spotting this :)

So the solution is to have the params on the solution "correct" for the "direct" launch (in that case `seneca.act({role: 'math', cmd: 'sum', left: process.argv[2], right: process.argv[3]}`...)and fix them when running with `run` and `verify`.

I will do a PR and check the params later for all the exercises

**Comment by marcopiraccini** [comment]
Ok, 0.1.15 should have fixed that
