### ISSUE TITLE
Problem description unclear

### ISSUE THREAD

**Issue by code-jace** [senecajs/seneca-in-practice#8]
I had a recurring error with exercise 3, 
solution had 'use strict' 
and module.exports used at top in code, as opposed to at the end (as done previously), with no explanation or hinting.
What was a simple change in code was causing fatal seneca error.

**Comment by marcopiraccini** [comment]
`use strict` enables the strict mode. Technically you can skip it, but I think that should be added to the "correct" answer. Not sure about "module export". In general there are a couple of ways of exporting stuff in modules, I think that `module.exports = function (...` is the mot elegant one. In which exercise do you find a different code? I've checked the proposed solutions and seems to be coherent to me.

**Comment by code-jace** [comment]
I was confused, as while it says to export the module in the first exercise, the example has it at the end of the code, but by exercise 3 it has the more elegant solution. Unless this is something natural to more experienced programmers, I did not pick up on it.

**Comment by marcopiraccini** [comment]
The first exercise says to export seneca, which is an Object. And this is basically a trick that we use to test the service without creating a plugin (introduced in the second exercise). 
The other "exports" are for plugins and are exports of functions. which can be done in this way: 

```
module.exports = function math (options) {
  this.add('role:math, cmd:sum', function (msg, respond) {
    var sum = msg.left + msg.right
    respond(null, {answer: sum})
  })
}
```

or in this way (similar to the first solution when exporting seneca). 

```
var myModule =  function math (options) {
  this.add('role:math, cmd:sum', function (msg, respond) {
    var sum = msg.left + msg.right
    respond(null, {answer: sum})
  })
}
module.exports = myModule
```

I prefer the first way, but the point is that we should find a way -in the first exercise- to avoid to export seneca in the solution, since it can be confusing. I'll open an issue for that.
